changelog:
  categories:
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Docs"
      labels:
        - "docs"
    - title: "Chore"
      labels:
        - "chore"
        - "maintenance"
    - title: "Dependencies"
      labels:
        - "dependencies"
  exclude:
    labels:
      - "skip-changelog"
